name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Chmod
        run: chmod +x ./gradlew

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.20
        with:
          labels: dependencies, gradle
          pr-title-template: 'build(deps): Bump Gradle Wrapper from %sourceVersion% to %targetVersion%'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
